### PR TITLE
Specify dependency on apple enterprise developer program

### PR DESCRIPTION
**Pull request by zhumo**
I think this is a requirement in order for you to sign your own APNS certs with a vendor cert? You have to be an approved MDM vendor. 

I was not able to get this to work otherwise. When I log into my apple developer account, I get no link to manage my certificates, as per the instructions. 
image

### CODE REVIEW

**Comment by np5** [comment]
You need a enterprise developer account and you also probably need to request the option to sign MDM CSR.

**Comment by np5** [comment]
Could you maybe change the wording ? It currently reads as if you could get the certificate under the enterprise developer portal. Maybe a separate sentence indicating that an enterprise developer account is required, with the MDM CSR option ?

**Comment by np5** [comment]
Thanks!

**Comment by headmin** [comment]
@zhumo As a follow up activity, please sign our individual CLA or would you need the Corporate Contributor License since your employer is involved?

**Comment by zhumo** [comment]
@headmin I'm not sure honestly. When do I do one or the other? Can you send them over?

**Pull request merged**
