### PR TITLE
Modular containers

### PR DESCRIPTION
**Pull request by groob**
Hi, 

I've made a few changes to the Dockerfile.
The main issue, is that a container should be as modular as possible(ideally, one process per container). 
This allows to compose, reuse and scale each component individually. 

I've made an attempt to split the django application from the rest - intending to run Postgres and Django as two separate containers. I ran into issue #2, but this container should work once that is resolved. 

We should strive to separate all services(elastic, kibana, redis etc) into independent services. 

Here are a few reference to more modular deployments of django apps
https://github.com/groob/docker-munkiwebadmin/tree/alpine
https://github.com/macadmins/sal

### CODE REVIEW

**Comment by groob** [comment]
Hi @np5, 

The [redis](https://github.com/zentralopensource/zentral/blob/9cc3494e54da16a125b8eb41ae8b675d3c3532b3/zentral/core/queues/backends/redisq.py) backend is still hardcoded to localhost, making it not possible to run with redis outside the Docker container. 

Here too: https://github.com/zentralopensource/zentral/blob/9cc3494e54da16a125b8eb41ae8b675d3c3532b3/zentral/contrib/inventory/backends/base.py

**Comment by np5** [comment]
In the [base inventory backend](https://github.com/zentralopensource/zentral/blob/9cc3494e54da16a125b8eb41ae8b675d3c3532b3/zentral/contrib/inventory/backends/base.py#L17-L19) and in the [redis queue backend](https://github.com/zentralopensource/zentral/blob/33d6918c69a10f65baef7dd172dc15a0645a64e3/zentral/core/queues/backends/redisq.py#L8-L10), we build an instance of the inventory or the store by passing them the relevant config part (config_d). We use the get method on the dict and only provide default values. You can override them by providing other values in the conf file.

So, you could use 

```json
"queues": {
  "backend": "zentral.core.queues.backends.redisq",
  "host": "10.0.17.3",
  "port": 7654,
  "db": 23
}
```

for the redis queue backend, and

```json
"zentral.contrib.inventory": {
  "backend": "zentral.contrib.inventory.backends.dummy",
  "redis_host": "10.0.17.3",
  "redis_post": 7654,
  "redis_db": 24
}
```

for the inventory app.

This is the standard construction for the different elements of zentral. Same with the actions. They receive the config dict when they are instantiated.

**Comment by groob** [comment]
I'll try that, thank you. 

Should I edit the Dockerfile to remove all external dependencies and resend the pull request?

**Comment by np5** [comment]
We want to maintain a docker container with everything in it so that everyone can start using zentral without having to manage multiple containers with the right connections between the containers and the proper start-up order. This is of course not acceptable in a production environment.

We could maybe rename this dockerfile as allinone.dockerfile and keep the bare minimum in the main Dockerfile.

The question is where do we stop dividing the containers. The backgroup zentral processes should run in a different container for example, if we want to be able to scale and deploy them independently from the django apps.

**Comment by np5** [comment]
There is a new dev env based on docker-machine in master now.

**Pull request closed without merging**
